### ISSUE TITLE
error

### ISSUE THREAD

**Issue by senhor-R** [IAmNirmesh/GrabARide#1]
![2018-04-11-215555_1366x768_scrot](https://user-images.githubusercontent.com/34902724/38650616-4b075706-3dd3-11e8-9ffe-34d865d463ce.png)

ERROR OPEN PROJECT

**Comment by IAmNirmesh** [comment]
It should work, because I am uploading the files only necessary for the project. Other files like settings, local.properties will go from your AndroidStudio locations.
Plus make sure you're using AndroidStudio 3.0.1 before updating the project. Also make sure you're connected to the internet. 

**One Suggestion though: Try it by removing all the *.iml files and reloading the project.**

**Comment by senhor-R** [comment]
![screenshot_1523550396](https://user-images.githubusercontent.com/34902724/38690826-756bab8c-3e55-11e8-8211-1dcf90c35a2f.png)

Help, don't show maps, my emulator api 27 Android Oreo 8.0

**Comment by IAmNirmesh** [comment]
Dude, this app has targetApi = 26, so Api 27 does not accept it.
Try with Api 26 once

**Comment by IAmNirmesh** [comment]
did it worked? or was it something else which you figured out?

**Comment by senhor-R** [comment]
HELP!! Android Studio 3.1.1, Emulator API 26
![screenshot_1523562944](https://user-images.githubusercontent.com/34902724/38700721-69139ff8-3e72-11e8-8214-7538cc823915.png)

**Comment by senhor-R** [comment]
HELP!

**Comment by senhor-R** [comment]
please send configuration you android studio.

**Comment by senhor-R** [comment]
look 

https://drive.google.com/open?id=0B9vwKOUoDudddGJCYl8tcU1uTjNKT3k4M3NUX3RoWE1NWkQ4

**Comment by IAmNirmesh** [comment]
1) Go to Project and delete whole .IML folder 
2) add task assemble{} as the very first line in root's build.gradle

3) Rebuild Project once again.

Besides, I think you should just create your own project with your own Firebase's jsons and just copy the code of respective packages and java files. Then you can have your own project which is linked to your google account. Right now, you just want to sneak out into my Google Account, which I think is little risky ;)

**Comment by senhor-R** [comment]
which key to put in


<string name="google_maps_key" templateMergeStrategy="preserve"` translatable="false">
        KEY
    </string>

**Comment by senhor-R** [comment]
Decline button this error 

E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: rahul.nirmesh.grabadrive, PID: 8509
                  java.lang.RuntimeException: Unable to resume activity {rahul.nirmesh.grabadrive/rahul.nirmesh.grabadrive.CustomerCall}: java.lang.IllegalStateException
                      at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3645)
                      at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3685)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1643)
                      at android.os.Handler.dispatchMessage(Handler.java:105)
                      at android.os.Looper.loop(Looper.java:164)
                      at android.app.ActivityThread.main(ActivityThread.java:6541)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
                   Caused by: java.lang.IllegalStateException
                      at android.media.MediaPlayer._start(Native Method)
                      at android.media.MediaPlayer.startImpl(MediaPlayer.java:1319)
                      at android.media.MediaPlayer.start(MediaPlayer.java:1294)
                      at rahul.nirmesh.grabadrive.CustomerCall.onResume(CustomerCall.java:106)
                      at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1354)
                      at android.app.Activity.performResume(Activity.java:7079)
                      at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3620)
                      at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3685) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1643) 
                      at android.os.Handler.dispatchMessage(Handler.java:105) 
                      at android.os.Looper.loop(Looper.java:164) 
                      at android.app.ActivityThread.main(ActivityThread.java:6541) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
E/UncaughtException: java.lang.RuntimeException: Unable to resume activity {rahul.nirmesh.grabadrive/rahul.nirmesh.grabadrive.CustomerCall}: java.lang.IllegalStateException
                         at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3645)
                         at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3685)
                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1643)
                         at android.os.Handler.dispatchMessage(Handler.java:105)
                         at android.os.Looper.loop(Looper.java:164)
                         at android.app.ActivityThread.main(ActivityThread.java:6541)
                         at java.lang.reflect.Method.invoke(Native Method)
                         at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
                      Caused by: java.lang.IllegalStateException
                         at android.media.MediaPlayer._start(Native Method)
                         at android.media.MediaPlayer.startImpl(MediaPlayer.java:1319)
                         at android.media.MediaPlayer.start(MediaPlayer.java:1294)
                         at rahul.nirmesh.grabadrive.CustomerCall.onResume(CustomerCall.java:106)
                         at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1354)
                         at android.app.Activity.performResume(Activity.java:7079)
                         at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3620)
                         at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3685) 
                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1643) 
                         at android.os.Handler.dispatchMessage(Handler.java:105) 
                         at android.os.Looper.loop(Looper.java:164) 
                         at android.app.ActivityThread.main(ActivityThread.java:6541) 
                         at java.lang.reflect.Method.invoke(Native Method) 
                         at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by IAmNirmesh** [comment]
are you trying to create your project or using my same project?
if you using my project then Key is already inside.
if you are using your new project, then you have to visit https://console.developers.google.com and create your own GoogleApiKey for this project.

**Comment by senhor-R** [comment]
I'm using my project

**Comment by senhor-R** [comment]
Decline button is in error

**Comment by senhor-R** [comment]
Brother, did you have a mistake?

**Comment by senhor-R** [comment]
2018-04-14 11:21 GMT-03:00 Rahul Nirmesh <notifications@github.com>:

**Comment by IAmNirmesh** [comment]
Driver:  https://drive.google.com/open?id=15x1MJEb3xoHqqEMJ-B8gdTbnOePx0Uhi

Rider:  https://drive.google.com/open?id=1YJja-tYJ6mUKY46km9dvUng90IgZX0yE

Download APKs, Register on two different devices, Login and test and do let me know if it looks like mistakes to you. Cheers!

**Comment by senhor-R** [comment]
![screenshot_1523808912](https://user-images.githubusercontent.com/34902724/38780588-7a6a8052-40af-11e8-81fa-10c724e39c5a.png)

Rider.apk  ERROR

**Comment by IAmNirmesh** [comment]
May I ask the Version you're using? Have you installed after checking "Unknown Sources"??
Honestly telling you, its all working great at my end.

**Comment by senhor-R** [comment]
Unknown Sources enable
api 26

try rebuild

**Comment by IAmNirmesh** [comment]
It has to work brother. I've given you the same APKs I'm using.

**Comment by senhor-R** [comment]
ok brother

**Comment by IAmNirmesh** [comment]
What else could I do for you? Send you the complete source code with all the files?
If yes, then send me your email id. 
But I would send you the same code as you already have. But still if you need it then I will do that too.

**Comment by senhor-R** [comment]
please send me mr.radamis@gmail.com
